---
- name: Create mysql database
  mysql_db: 
    name={{ wp_mysql_db }} 
    state=present
  sudo: yes

- name: Create mysql user
  sudo: yes
  mysql_user:
    name={{ wp_mysql_user }}
    password={{ wp_mysql_password }}
    priv=*.*:ALL
# tasks file for mysql
